import type { CSSProperties } from "react";
import { DEFAULT_TRACKER_CARD_ACCENT, getTrackerCardStyleVars } from "../../../shared/lib/tracker-card-colors";
import type { TrackerProfilePalette } from "./tracker-profile-colors";

type TrackerProfileStyle = CSSProperties & Record<`--${string}`, string | undefined>;

export function withTrackerProfileStyle(palette: TrackerProfilePalette, background?: string): CSSProperties {
  const vars = getTrackerCardStyleVars({ palette, background });
  const style: TrackerProfileStyle = {
    "--tracker-profile-accent": vars.accent,
    "--tracker-profile-accent-highlight-opacity": vars.accentHighlightOpacity,
    "--tracker-profile-accent-layer": vars.accentLayer,
    "--tracker-profile-accent-solid": vars.accentSolid,
    "--tracker-profile-accent-wash-opacity": vars.accentWashOpacity,
    "--tracker-profile-body-rule-opacity": vars.bodyRuleOpacity,
    "--tracker-profile-body-wash-opacity": vars.bodyWashOpacity,
    "--tracker-profile-dialogue": vars.accent,
    "--tracker-profile-dialogue-border": vars.dialogueBorder,
    "--tracker-profile-dialogue-glow": vars.dialogueGlow,
    "--tracker-profile-display-layer": vars.displayLayer,
    "--tracker-profile-display-solid": vars.displaySolid,
    "--tracker-profile-display-rail-opacity": vars.displayRailOpacity,
    "--tracker-profile-field-material": vars.fieldMaterial,
    "--tracker-profile-field-material-blend": vars.fieldMaterialBlend,
    "--tracker-profile-glow-opacity": vars.glowOpacity,
    "--tracker-profile-icon": vars.icon,
    "--tracker-profile-label-icon": vars.labelIcon,
    "--tracker-profile-label-muted-text": vars.labelMutedText,
    "--tracker-profile-label-text": vars.labelText,
    "--tracker-profile-box": vars.box,
    "--tracker-profile-box-layer": vars.boxLayer,
    "--tracker-profile-frame": vars.frame,
    "--tracker-profile-frame-blend": vars.frameBlend,
    "--tracker-profile-material": vars.material,
    "--tracker-profile-material-blend": vars.materialBlend,
    "--tracker-profile-panel": vars.panel,
    "--tracker-profile-panel-blend": vars.panelBlend,
    "--tracker-profile-panel-material": vars.panelMaterial,
    "--tracker-profile-panel-material-blend": vars.panelMaterialBlend,
    "--tracker-profile-panel-strong": vars.panelStrong,
    "--tracker-profile-panel-strong-blend": vars.panelStrongBlend,
    "--tracker-profile-portrait-base": vars.portraitBase,
    "--tracker-profile-portrait-bottom-glow-opacity": vars.portraitBottomGlowOpacity,
    "--tracker-profile-portrait-bottom-rule-opacity": vars.portraitBottomRuleOpacity,
    "--tracker-profile-portrait-media-blur": vars.portraitMediaBlur,
    "--tracker-profile-portrait-media-opacity": vars.portraitMediaOpacity,
    "--tracker-profile-portrait-media-saturate": vars.portraitMediaSaturate,
    "--tracker-profile-portrait-light": vars.portraitLight,
    "--tracker-profile-portrait-light-opacity": vars.portraitLightOpacity,
    "--tracker-profile-portrait-rim": vars.portraitRim,
    "--tracker-profile-portrait-rim-opacity": vars.portraitRimOpacity,
    "--tracker-profile-portrait-side-mask-opacity": vars.portraitSideMaskOpacity,
    "--tracker-profile-portrait-veil": vars.portraitVeil,
    "--tracker-profile-muted-panel": vars.mutedPanel,
    "--tracker-profile-muted-panel-blend": vars.mutedPanelBlend,
    "--tracker-profile-nameplate": vars.nameplate,
    "--tracker-profile-nameplate-glow": vars.nameplateGlow,
    "--tracker-profile-nameplate-rule": vars.nameplateRule,
    "--tracker-profile-nameplate-text": vars.nameplateText,
    "--tracker-profile-rule": vars.rule,
    "--tracker-profile-surface": vars.surface,
    "--tracker-profile-surface-blend": vars.surfaceBlend,
    "--tracker-profile-surface-layer": vars.surfaceLayer,
    "--tracker-profile-surface-solid": vars.surfaceSolid,
    "--tracker-profile-slot-rule": vars.slotRule,
    "--tracker-profile-slot-shadow": vars.slotShadow,
    "--tracker-profile-slot-surface": vars.slotSurface,
    "--tracker-profile-slot-surface-blend": vars.slotSurfaceBlend,
    "--tracker-profile-tint-opacity": vars.tintOpacity,
    "--tracker-profile-display-opacity": vars.displayOpacity,
    "--tracker-profile-contrast-soft-top": vars.contrastSoftTop,
    "--tracker-profile-contrast-soft-mid": vars.contrastSoftMid,
    "--tracker-profile-contrast-soft-bottom": vars.contrastSoftBottom,
    "--tracker-profile-contrast-strong-top": vars.contrastStrongTop,
    "--tracker-profile-contrast-strong-mid": vars.contrastStrongMid,
    "--tracker-profile-contrast-strong-bottom": vars.contrastStrongBottom,
    "--tracker-profile-muted-text": vars.mutedText,
    "--tracker-profile-number-text": vars.numberText,
    "--tracker-profile-row-rule": vars.rowRule,
    "--tracker-profile-stat-fill-glow": vars.statFillGlow,
    "--tracker-profile-stat-fill-highlight": vars.statFillHighlight,
    "--tracker-profile-stat-track": vars.statTrack,
    "--tracker-profile-stat-track-blend": vars.statTrackBlend,
    "--tracker-profile-stat-track-ring": vars.statTrackRing,
    "--tracker-profile-stat-track-shadow": vars.statTrackShadow,
    "--tracker-profile-text": vars.text,
    "--tracker-inline-foreground": "var(--tracker-profile-text)",
    "--tracker-inline-muted": "var(--tracker-profile-muted-text)",
    "--tracker-inline-number": "var(--tracker-profile-number-text)",
    "--tracker-inline-rule": "var(--tracker-profile-row-rule)",
    background: vars.background,
    backgroundBlendMode: vars.backgroundBlendMode,
  };

  if (palette.accent !== DEFAULT_TRACKER_CARD_ACCENT) {
    style["--primary"] = vars.accent;
  }

  return style;
}
